# Generated by Django 4.0.1 on 2022-01-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('BookTitle', models.CharField(max_length=100, verbose_name='Название Книги')),
                ('Author', models.CharField(default='Неизвестен', max_length=50, verbose_name='Автор')),
                ('Year', models.IntegerField(default=0, verbose_name='Год')),
                ('Position', models.CharField(default=None, max_length=4, unique=True, verbose_name='Ячейка')),
                ('Description', models.TextField(default='Простое описание', verbose_name='Описание')),
                ('InfoForDocuments', models.TextField(default='В конец', verbose_name='Для ссылок в библиографический список')),
                ('Free', models.BooleanField(default=True, verbose_name='Наличие')),
                ('Img', models.ImageField(upload_to='static/UploadImg', verbose_name='Img')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
