# Generated by Django 4.0.1 on 2022-01-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_comments_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='DateFirst',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала аренды'),
        ),
        migrations.AddField(
            model_name='books',
            name='DateSecond',
            field=models.DateField(blank=True, null=True, verbose_name='Дата возврата'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='moderation',
            field=models.BooleanField(default=True, verbose_name='Модерация'),
        ),
    ]
