# Generated by Django 4.0.1 on 2022-01-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_books_datefirst_books_datesecond_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Reader',
            field=models.TextField(null=True, verbose_name='Кто взял книгу'),
        ),
    ]
