# Generated by Django 4.0.1 on 2022-01-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_books_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Reader',
            field=models.CharField(max_length=100, null=True, verbose_name='Кто взял книгу'),
        ),
    ]
